### ISSUE TITLE
one test failure

### ISSUE THREAD

**Issue by bthirion** [sjdavenport/pyrft#12]
===================================================================================== short test summary info ======================================================================================
FAILED tests/test_fdp.py::test_fdr_bh - AssertionError: assert False

>       assert isinstance(n_rejections, np.intc)
E       AssertionError: assert False
E        +  where False = isinstance(4, <class 'numpy.int32'>)
E        +    where <class 'numpy.int32'> = np.intc

tests/test_fdp.py:22: AssertionError

on my box, n_rejections is a numpy.int64.

Do you simply want to test if this an integer, as opposed to a float ?

**Comment by sjdavenport** [comment]
Hmmm that's strange, for me that test works and isinstance(n_rejections, np.int64) is false. 

Are integer classes defined different across different python packages?

Yes that's right, that's what I'm trying to test are there other ways of doing that?

**Comment by bthirion** [comment]
The point is that you probably don't ware whether it's np.int64 or np.int32. Maybe `assert x == (int)x)`

**Comment by sjdavenport** [comment]
Ah okay thanks good suggestion
