### ISSUE TITLE
t_linear >> linear_template in sanssouci.python

### ISSUE THREAD

**Issue by pneuvial** [sjdavenport/pyrft#17]
There has been a change in the API of the sanssouci.python package: `t_linear` is now named more  explicitly: `linear_template`. Idem for the corresponding inverse function and other templates. The corresponding code in pyrft should be updated accordingly, in particular in:

https://github.com/sjdavenport/pyrft/blob/9087715614ece386a758fadffdf85680e4ec735d/pyrft/ss_extras.py#L106-L111

**Comment by sjdavenport** [comment]
Alex fixed this
