### ISSUE TITLE
Enforce pep8 conventions

### ISSUE THREAD

**Issue by bthirion** [sjdavenport/pyrft#5]
Please systematically enforce Python style conventions.
For that the easiest solution is to have a linter in you preferred editor that outlines all syntax violations.
It is important, because you want people to be able to read and understand your code easily.

**Comment by sjdavenport** [comment]
Ah sure I'm happy to do so, could you explain what a linter is? Are there specific conventions that I am currently violating?

**Comment by bthirion** [comment]
The conventions are here: `https://www.python.org/dev/peps/pep-0008/`
About linters: https://realpython.com/python-code-quality/
The point is that you need to learn the rules for Python coding, so it's better if your editor can teach them directly :-)

**Comment by sjdavenport** [comment]
Okay thanks I will look into this!

**Comment by sjdavenport** [comment]
Hey Bertrand, so I analysed the code using a linter and there seem to be several main violations:

1) Trailing whitespace (often in the comment sections)

2) Variables not conforming to snake_case naming. 

3) Indentation not being standard.

4) The number of function arguments being too many.

Are these the ones you are referring to, or are you thinking of something else?

**Comment by sjdavenport** [comment]
Certainly happy to most of these, though for some functions I do need extra arguments.

**Comment by bthirion** [comment]
> Are these the ones you are referring to, or are you thinking of something else?

These indeed.  (Sorry, I'm not very reponsive atm)

**Comment by sjdavenport** [comment]
Okay cool, just wanted to clarify that! (no worries!)

**Comment by sjdavenport** [comment]
I have updated the main function files so that these issues are mainly fixed (they now have a a score of around 8.5/10 instead of -8/10!).

**Comment by bthirion** [comment]
Congratulations ! 

Let me advise to update the code through Pull requests: this opens the possibility to have discussion on the code, and is very useful when it comes to improving the API.

**Comment by sjdavenport** [comment]
Okay I'll keep that in mind and will ask you to elaborate on that on Wednesday.
