### ISSUE TITLE
Do we need a Field class ?

### ISSUE THREAD

**Issue by bthirion** [sjdavenport/pyrft#7]
I'm wondering whether we need a Field class ?
To me this is exactly a masked array, which a standard Numpy type. Is there anything needs or can do, that is not already available for Numpy masked arrays ? If there is nothing, then we should preferably rely on a standard  masked Array. With the cirrent code, you force people to understand what a Field is, since you use it in examples...

**Comment by sjdavenport** [comment]
The field class does a number of things that the numpy masked array doesn't. For instance it allows you to have data over subjects as well as over space (with the mask just over space).

**Comment by bthirion** [comment]
I don't see why you can't have these features with a masked array. Best, B

**Comment by sjdavenport** [comment]
Can you give me an example?

Ie something similar to the output of

pr.wfield((50,50), 25)

but with a 2D mask that is not just ones.

**Comment by bthirion** [comment]
```
shape = (50, 50, 1)
n_samples = 25
mask = np.tile(np.random.rand(*shape) > .5, (1, 1, n_samples))
x = np.ma.masked_array(np.random.randn(50, 50, 25), mask) 
```

**Comment by sjdavenport** [comment]
Right but in this example the mask is 3D not 2D which makes it more difficult to use and when you have lots of subjects such a big 3D mask will take up a lot of memory space and will slow everything down. 

It's also unclear how do you would distinguish between a (50,50) 2D array with 25 subjects and a (50,50,25) 3D array (with 1 subject), which is one of the advantages of the field class.

**Comment by bthirion** [comment]
I take your point. ```
But if the object is simply a container, you can simply make it a NamedTuple, with (n+1 dimensional) `data` and (n dimensional) `mask`. The only thing to do is check that data and mask have a consistent shape.

**Comment by sjdavenport** [comment]
Well the consistency e.g. between the data and the mask is hard coded into the field class (other with a number of other compatibility constraints e.g. on D and fibersize/nsubj). So if you try to change the mask to something that doesn't match the size of the data (for a field class object) then you get an error. This compatility constrainsts are very useful because the user might (by mistake) try to change the mask to something that didn't match the data. A NamedTuple doesn't do this.

**Comment by sjdavenport** [comment]
(At least as far as I am aware :) )

**Comment by sjdavenport** [comment]
Can I close this issue? I think we've kind of agreed that there are a number of advantages to the field class.

**Comment by bthirion** [comment]
I'm not convinved, but let's move on and close it for the time being.

**Comment by sjdavenport** [comment]
Okay!
