### ISSUE TITLE
Tests suite is broken

### ISSUE THREAD

**Issue by bthirion** [sjdavenport/pyrft#9]
Pytest returns identation-related errors.

**Comment by bthirion** [comment]
```
======================================================================= test session starts =======================================================================
platform linux2 -- Python 2.7.18, pytest-4.6.9, py-1.8.1, pluggy-0.13.0
rootdir: /home/bertrand/mygit/pyrft
collected 0 items / 4 errors                                                                                                                                      

============================================================================= ERRORS ==============================================================================
__________________________________________________________ ERROR collecting tests/test_bootstrapping.py ___________________________________________________________
ImportError while importing test module '/home/bertrand/mygit/pyrft/tests/test_bootstrapping.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test_bootstrapping.py:4: in <module>
    import pyrft as pr
E   ImportError: No module named pyrft
_________________________________________________________ ERROR collecting tests/test_contrast_tstats.py __________________________________________________________
/usr/lib/python2.7/dist-packages/_pytest/python.py:507: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
/usr/lib/python2.7/dist-packages/py/_path/local.py:701: in pyimport
    __import__(modname)
E     File "/home/bertrand/mygit/pyrft/tests/test_contrast_tstats.py", line 39
E       XTXinv = np.linalg.inv(X.T @ X)
E                                  ^
E   SyntaxError: invalid syntax
____________________________________________________________ ERROR collecting tests/test_permuting.py _____________________________________________________________
/usr/lib/python2.7/dist-packages/_pytest/python.py:507: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
/usr/lib/python2.7/dist-packages/py/_path/local.py:701: in pyimport
    __import__(modname)
E     File "/home/bertrand/mygit/pyrft/tests/test_permuting.py", line 8
E       categ =
E              ^
E   SyntaxError: invalid syntax
_________________________________________________ ERROR collecting tests/Testing_stats_functions/test_mvtstat.py __________________________________________________
/usr/lib/python2.7/dist-packages/_pytest/python.py:507: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
/usr/lib/python2.7/dist-packages/py/_path/local.py:701: in pyimport
    __import__(modname)
E     File "/home/bertrand/mygit/pyrft/tests/Testing_stats_functions/test_mvtstat.py", line 2
E       sD = np.shape(data)
E      ^
E   IndentationError: unexpected indent
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 4 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
===================================================================== 4 error in 0.10 seconds =====================================================================
bertrand@laptop:~/mygit/pyrft/tests$ 
```

**Comment by bthirion** [comment]
This one should be handled in priority: we need working unit tests to be able to edit the code without breaking it...

**Comment by sjdavenport** [comment]
I will attend to this this week. I've added an example below so you can see what these will look like.

import numpy as np
import pyrft as pr
import os

# The location where the pyrft module is saved (need to specify yourself)
pyrft_loc = 'C:/Users/12SDa/davenpor/davenpor/Toolboxes/pyrft/'

# Where data is stored
data_store = pyrft_loc + 'tests2/test_data/'

def test_boot_contrasts():
    np.random.seed(10)
    Dim = 5; N = 30; categ = np.random.multinomial(2, [1/3,1/3,1/3], size = N)[:,1]
    X = pr.groupX(categ); C = np.array([[1,-1,0],[0,1,-1]]); lat_data = pr.wfield(Dim,N)
    minP, orig_pvalues, pivotal_stats, _ = pr.boot_contrasts(lat_data, X, C)
    
    file_name = 'test_boot_contrasts_data.npz'
    file_loc = data_store + file_name
    if not os.path.exists(file_loc):
       np.savez(file_loc, minP = minP, orig_pvalues = orig_pvalues.field, pivotal_stats = pivotal_stats)
    else:
       results = np.load(file_loc, allow_pickle = True)
       assert((minP == results['minP']).all())
       assert((orig_pvalues.field == results['orig_pvalues']).all())
       assert((pivotal_stats == results['pivotal_stats']).all())

**Comment by bthirion** [comment]
No, that's not what is expected here.
If you want I can draft a test, but unfortunately I won't be able to make it in the next two days.
Best,

**Comment by sjdavenport** [comment]
Okay yeah a draft would be helpful. As I understood the purpose of the test function was to ensure that is you changed something within the function the output didn't change? But perhaps I misunderstood that!

**Comment by bthirion** [comment]
More importantly, It is important to ensure that a change somewhere does not break the code (or the underlying logic) in some other place throughside effects. 
B

**Comment by sjdavenport** [comment]
Btw the really big bold writing above are supposed to be comments in the code - it seems that in github writing here the hastag makes things bigger! You probably realised that but just thought that I would clarify!!

**Comment by sjdavenport** [comment]
Ah just saw you wrote a response - yes I can see that is important of course.

**Comment by sjdavenport** [comment]
Hey, I have added the test functions which should now work! Happy to make changes/improvements to them - let's discuss.

**Comment by bthirion** [comment]
Can you create a pull request to discuss these changes ?

**Comment by sjdavenport** [comment]
I already did, I created a testing branch and submitted a pull request

**Comment by bthirion** [comment]
OK, thx. I don't get the notifications.

**Comment by sjdavenport** [comment]
Ah okay no worries! :)

**Comment by sjdavenport** [comment]
Hey so I've addressed your comments. I have left a few comments where I have queries but have otherwise changed the things that you suggested.

**Comment by sjdavenport** [comment]
I've also removed the binary files.

**Comment by sjdavenport** [comment]
Hey Bertrand, thanks for your latest comments. I think you may not have noticed that a number of the pep8 conventions were fixed last week, e.g. the I to i change on the testing branch. Can I merge it now?

I have included a number of your suggestions and left a few comments to your comments on the other ones. It feels like we have a few stylistic coding differences (non-pep8), that it would be best to discuss in person than via comments. E.g. I think that what happens within the example section should be what is most amenable to apply copy pasting as that is the primary use for examples.

**Comment by bthirion** [comment]
Sure you can merge.

**Comment by sjdavenport** [comment]
Okay thanks!

**Comment by sjdavenport** [comment]
Hey I merged the pull requests and now I can't find the comments on the pull request, is there a way to view the comments on a merged pull request?

**Comment by sjdavenport** [comment]
Ah I figured it out never mind!

**Comment by sjdavenport** [comment]
I have now fixed the indentation within the docstrings (including the examples sections :) ) and modified the spacing.

**Comment by bthirion** [comment]
Closing this for now.
